export const NEETCODE_TOPICS = [
  { name: "Arrays & Hashing", total: 9 },
  { name: "Two Pointers", total: 5 },
  { name: "Sliding Window", total: 6 },
  { name: "Stack", total: 7 },
  { name: "Binary Search", total: 7 },
  { name: "Linked List", total: 11 },
  { name: "Trees", total: 15 },
  { name: "Tries", total: 3 },
  { name: "Heap / Priority Queue", total: 7 },
  { name: "Backtracking", total: 9 },
  { name: "Graphs", total: 13 },
  { name: "Advanced Graphs", total: 6 },
  { name: "1-D Dynamic Programming", total: 12 },
  { name: "2-D Dynamic Programming", total: 11 },
  { name: "Greedy", total: 8 },
  { name: "Intervals", total: 6 },
  { name: "Math & Geometry", total: 8 },
  { name: "Bit Manipulation", total: 7 },
] as const;

export const DIFFICULTY_COLORS = {
  easy: {
    bg: "bg-emerald-500/15",
    text: "text-emerald-400",
    dot: "bg-emerald-400",
  },
  medium: {
    bg: "bg-amber-500/15",
    text: "text-amber-400",
    dot: "bg-amber-400",
  },
  hard: { bg: "bg-red-500/15", text: "text-red-400", dot: "bg-red-400" },
} as const;

export const STATUS_COLORS = {
  solved: { bg: "bg-emerald-500/15", text: "text-emerald-400" },
  attempted: { bg: "bg-amber-500/15", text: "text-amber-400" },
  revisit: { bg: "bg-sky-500/15", text: "text-sky-400" },
} as const;

export const LANGUAGES = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
] as const;

export const NEETCODE_QUESTIONS: {
  title: string;
  leetcode_num: number;
  difficulty: "easy" | "medium" | "hard";
  topic: string;
  slug: string;
}[] = [
  // Arrays & Hashing
  {
    title: "Contains Duplicate",
    leetcode_num: 217,
    difficulty: "easy",
    topic: "Arrays & Hashing",
    slug: "contains-duplicate",
  },
  {
    title: "Valid Anagram",
    leetcode_num: 242,
    difficulty: "easy",
    topic: "Arrays & Hashing",
    slug: "valid-anagram",
  },
  {
    title: "Two Sum",
    leetcode_num: 1,
    difficulty: "easy",
    topic: "Arrays & Hashing",
    slug: "two-sum",
  },
  {
    title: "Group Anagrams",
    leetcode_num: 49,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "group-anagrams",
  },
  {
    title: "Top K Frequent Elements",
    leetcode_num: 347,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "top-k-frequent-elements",
  },
  {
    title: "Encode and Decode Strings",
    leetcode_num: 271,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "encode-and-decode-strings",
  },
  {
    title: "Product of Array Except Self",
    leetcode_num: 238,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "product-of-array-except-self",
  },
  {
    title: "Valid Sudoku",
    leetcode_num: 36,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "valid-sudoku",
  },
  {
    title: "Longest Consecutive Sequence",
    leetcode_num: 128,
    difficulty: "medium",
    topic: "Arrays & Hashing",
    slug: "longest-consecutive-sequence",
  },

  // Two Pointers
  {
    title: "Valid Palindrome",
    leetcode_num: 125,
    difficulty: "easy",
    topic: "Two Pointers",
    slug: "valid-palindrome",
  },
  {
    title: "Two Sum II",
    leetcode_num: 167,
    difficulty: "medium",
    topic: "Two Pointers",
    slug: "two-sum-ii-input-array-is-sorted",
  },
  {
    title: "3Sum",
    leetcode_num: 15,
    difficulty: "medium",
    topic: "Two Pointers",
    slug: "3sum",
  },
  {
    title: "Container With Most Water",
    leetcode_num: 11,
    difficulty: "medium",
    topic: "Two Pointers",
    slug: "container-with-most-water",
  },
  {
    title: "Trapping Rain Water",
    leetcode_num: 42,
    difficulty: "hard",
    topic: "Two Pointers",
    slug: "trapping-rain-water",
  },

  // Sliding Window
  {
    title: "Best Time to Buy and Sell Stock",
    leetcode_num: 121,
    difficulty: "easy",
    topic: "Sliding Window",
    slug: "best-time-to-buy-and-sell-stock",
  },
  {
    title: "Longest Substring Without Repeating Characters",
    leetcode_num: 3,
    difficulty: "medium",
    topic: "Sliding Window",
    slug: "longest-substring-without-repeating-characters",
  },
  {
    title: "Longest Repeating Character Replacement",
    leetcode_num: 424,
    difficulty: "medium",
    topic: "Sliding Window",
    slug: "longest-repeating-character-replacement",
  },
  {
    title: "Permutation in String",
    leetcode_num: 567,
    difficulty: "medium",
    topic: "Sliding Window",
    slug: "permutation-in-string",
  },
  {
    title: "Minimum Window Substring",
    leetcode_num: 76,
    difficulty: "hard",
    topic: "Sliding Window",
    slug: "minimum-window-substring",
  },
  {
    title: "Sliding Window Maximum",
    leetcode_num: 239,
    difficulty: "hard",
    topic: "Sliding Window",
    slug: "sliding-window-maximum",
  },

  // Stack
  {
    title: "Valid Parentheses",
    leetcode_num: 20,
    difficulty: "easy",
    topic: "Stack",
    slug: "valid-parentheses",
  },
  {
    title: "Min Stack",
    leetcode_num: 155,
    difficulty: "medium",
    topic: "Stack",
    slug: "min-stack",
  },
  {
    title: "Evaluate Reverse Polish Notation",
    leetcode_num: 150,
    difficulty: "medium",
    topic: "Stack",
    slug: "evaluate-reverse-polish-notation",
  },
  {
    title: "Generate Parentheses",
    leetcode_num: 22,
    difficulty: "medium",
    topic: "Stack",
    slug: "generate-parentheses",
  },
  {
    title: "Daily Temperatures",
    leetcode_num: 739,
    difficulty: "medium",
    topic: "Stack",
    slug: "daily-temperatures",
  },
  {
    title: "Car Fleet",
    leetcode_num: 853,
    difficulty: "medium",
    topic: "Stack",
    slug: "car-fleet",
  },
  {
    title: "Largest Rectangle in Histogram",
    leetcode_num: 84,
    difficulty: "hard",
    topic: "Stack",
    slug: "largest-rectangle-in-histogram",
  },

  // Binary Search
  {
    title: "Binary Search",
    leetcode_num: 704,
    difficulty: "easy",
    topic: "Binary Search",
    slug: "binary-search",
  },
  {
    title: "Search a 2D Matrix",
    leetcode_num: 74,
    difficulty: "medium",
    topic: "Binary Search",
    slug: "search-a-2d-matrix",
  },
  {
    title: "Koko Eating Bananas",
    leetcode_num: 875,
    difficulty: "medium",
    topic: "Binary Search",
    slug: "koko-eating-bananas",
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    leetcode_num: 153,
    difficulty: "medium",
    topic: "Binary Search",
    slug: "find-minimum-in-rotated-sorted-array",
  },
  {
    title: "Search in Rotated Sorted Array",
    leetcode_num: 33,
    difficulty: "medium",
    topic: "Binary Search",
    slug: "search-in-rotated-sorted-array",
  },
  {
    title: "Time Based Key-Value Store",
    leetcode_num: 981,
    difficulty: "medium",
    topic: "Binary Search",
    slug: "time-based-key-value-store",
  },
  {
    title: "Median of Two Sorted Arrays",
    leetcode_num: 4,
    difficulty: "hard",
    topic: "Binary Search",
    slug: "median-of-two-sorted-arrays",
  },

  // Linked List
  {
    title: "Reverse Linked List",
    leetcode_num: 206,
    difficulty: "easy",
    topic: "Linked List",
    slug: "reverse-linked-list",
  },
  {
    title: "Merge Two Sorted Lists",
    leetcode_num: 21,
    difficulty: "easy",
    topic: "Linked List",
    slug: "merge-two-sorted-lists",
  },
  {
    title: "Linked List Cycle",
    leetcode_num: 141,
    difficulty: "easy",
    topic: "Linked List",
    slug: "linked-list-cycle",
  },
  {
    title: "Reorder List",
    leetcode_num: 143,
    difficulty: "medium",
    topic: "Linked List",
    slug: "reorder-list",
  },
  {
    title: "Remove Nth Node From End of List",
    leetcode_num: 19,
    difficulty: "medium",
    topic: "Linked List",
    slug: "remove-nth-node-from-end-of-list",
  },
  {
    title: "Copy List with Random Pointer",
    leetcode_num: 138,
    difficulty: "medium",
    topic: "Linked List",
    slug: "copy-list-with-random-pointer",
  },
  {
    title: "Add Two Numbers",
    leetcode_num: 2,
    difficulty: "medium",
    topic: "Linked List",
    slug: "add-two-numbers",
  },
  {
    title: "Find the Duplicate Number",
    leetcode_num: 287,
    difficulty: "medium",
    topic: "Linked List",
    slug: "find-the-duplicate-number",
  },
  {
    title: "LRU Cache",
    leetcode_num: 146,
    difficulty: "medium",
    topic: "Linked List",
    slug: "lru-cache",
  },
  {
    title: "Merge K Sorted Lists",
    leetcode_num: 23,
    difficulty: "hard",
    topic: "Linked List",
    slug: "merge-k-sorted-lists",
  },
  {
    title: "Reverse Nodes in K-Group",
    leetcode_num: 25,
    difficulty: "hard",
    topic: "Linked List",
    slug: "reverse-nodes-in-k-group",
  },

  // Trees
  {
    title: "Invert Binary Tree",
    leetcode_num: 226,
    difficulty: "easy",
    topic: "Trees",
    slug: "invert-binary-tree",
  },
  {
    title: "Maximum Depth of Binary Tree",
    leetcode_num: 104,
    difficulty: "easy",
    topic: "Trees",
    slug: "maximum-depth-of-binary-tree",
  },
  {
    title: "Diameter of Binary Tree",
    leetcode_num: 543,
    difficulty: "easy",
    topic: "Trees",
    slug: "diameter-of-binary-tree",
  },
  {
    title: "Balanced Binary Tree",
    leetcode_num: 110,
    difficulty: "easy",
    topic: "Trees",
    slug: "balanced-binary-tree",
  },
  {
    title: "Same Tree",
    leetcode_num: 100,
    difficulty: "easy",
    topic: "Trees",
    slug: "same-tree",
  },
  {
    title: "Subtree of Another Tree",
    leetcode_num: 572,
    difficulty: "easy",
    topic: "Trees",
    slug: "subtree-of-another-tree",
  },
  {
    title: "Lowest Common Ancestor of a BST",
    leetcode_num: 235,
    difficulty: "medium",
    topic: "Trees",
    slug: "lowest-common-ancestor-of-a-binary-search-tree",
  },
  {
    title: "Binary Tree Level Order Traversal",
    leetcode_num: 102,
    difficulty: "medium",
    topic: "Trees",
    slug: "binary-tree-level-order-traversal",
  },
  {
    title: "Binary Tree Right Side View",
    leetcode_num: 199,
    difficulty: "medium",
    topic: "Trees",
    slug: "binary-tree-right-side-view",
  },
  {
    title: "Count Good Nodes in Binary Tree",
    leetcode_num: 1448,
    difficulty: "medium",
    topic: "Trees",
    slug: "count-good-nodes-in-binary-tree",
  },
  {
    title: "Validate Binary Search Tree",
    leetcode_num: 98,
    difficulty: "medium",
    topic: "Trees",
    slug: "validate-binary-search-tree",
  },
  {
    title: "Kth Smallest Element in a BST",
    leetcode_num: 230,
    difficulty: "medium",
    topic: "Trees",
    slug: "kth-smallest-element-in-a-bst",
  },
  {
    title: "Construct Binary Tree from Preorder and Inorder",
    leetcode_num: 105,
    difficulty: "medium",
    topic: "Trees",
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
  },
  {
    title: "Binary Tree Maximum Path Sum",
    leetcode_num: 124,
    difficulty: "hard",
    topic: "Trees",
    slug: "binary-tree-maximum-path-sum",
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    leetcode_num: 297,
    difficulty: "hard",
    topic: "Trees",
    slug: "serialize-and-deserialize-binary-tree",
  },

  // Tries
  {
    title: "Implement Trie (Prefix Tree)",
    leetcode_num: 208,
    difficulty: "medium",
    topic: "Tries",
    slug: "implement-trie-prefix-tree",
  },
  {
    title: "Design Add and Search Words Data Structure",
    leetcode_num: 211,
    difficulty: "medium",
    topic: "Tries",
    slug: "design-add-and-search-words-data-structure",
  },
  {
    title: "Word Search II",
    leetcode_num: 212,
    difficulty: "hard",
    topic: "Tries",
    slug: "word-search-ii",
  },

  // Heap / Priority Queue
  {
    title: "Kth Largest Element in a Stream",
    leetcode_num: 703,
    difficulty: "easy",
    topic: "Heap / Priority Queue",
    slug: "kth-largest-element-in-a-stream",
  },
  {
    title: "Last Stone Weight",
    leetcode_num: 1046,
    difficulty: "easy",
    topic: "Heap / Priority Queue",
    slug: "last-stone-weight",
  },
  {
    title: "K Closest Points to Origin",
    leetcode_num: 973,
    difficulty: "medium",
    topic: "Heap / Priority Queue",
    slug: "k-closest-points-to-origin",
  },
  {
    title: "Kth Largest Element in an Array",
    leetcode_num: 215,
    difficulty: "medium",
    topic: "Heap / Priority Queue",
    slug: "kth-largest-element-in-an-array",
  },
  {
    title: "Task Scheduler",
    leetcode_num: 621,
    difficulty: "medium",
    topic: "Heap / Priority Queue",
    slug: "task-scheduler",
  },
  {
    title: "Design Twitter",
    leetcode_num: 355,
    difficulty: "medium",
    topic: "Heap / Priority Queue",
    slug: "design-twitter",
  },
  {
    title: "Find Median from Data Stream",
    leetcode_num: 295,
    difficulty: "hard",
    topic: "Heap / Priority Queue",
    slug: "find-median-from-data-stream",
  },

  // Backtracking
  {
    title: "Subsets",
    leetcode_num: 78,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "subsets",
  },
  {
    title: "Combination Sum",
    leetcode_num: 39,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "combination-sum",
  },
  {
    title: "Permutations",
    leetcode_num: 46,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "permutations",
  },
  {
    title: "Subsets II",
    leetcode_num: 90,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "subsets-ii",
  },
  {
    title: "Combination Sum II",
    leetcode_num: 40,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "combination-sum-ii",
  },
  {
    title: "Word Search",
    leetcode_num: 79,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "word-search",
  },
  {
    title: "Palindrome Partitioning",
    leetcode_num: 131,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "palindrome-partitioning",
  },
  {
    title: "Letter Combinations of a Phone Number",
    leetcode_num: 17,
    difficulty: "medium",
    topic: "Backtracking",
    slug: "letter-combinations-of-a-phone-number",
  },
  {
    title: "N-Queens",
    leetcode_num: 51,
    difficulty: "hard",
    topic: "Backtracking",
    slug: "n-queens",
  },

  // Graphs
  {
    title: "Number of Islands",
    leetcode_num: 200,
    difficulty: "medium",
    topic: "Graphs",
    slug: "number-of-islands",
  },
  {
    title: "Max Area of Island",
    leetcode_num: 695,
    difficulty: "medium",
    topic: "Graphs",
    slug: "max-area-of-island",
  },
  {
    title: "Clone Graph",
    leetcode_num: 133,
    difficulty: "medium",
    topic: "Graphs",
    slug: "clone-graph",
  },
  {
    title: "Walls and Gates",
    leetcode_num: 286,
    difficulty: "medium",
    topic: "Graphs",
    slug: "walls-and-gates",
  },
  {
    title: "Rotting Oranges",
    leetcode_num: 994,
    difficulty: "medium",
    topic: "Graphs",
    slug: "rotting-oranges",
  },
  {
    title: "Pacific Atlantic Water Flow",
    leetcode_num: 417,
    difficulty: "medium",
    topic: "Graphs",
    slug: "pacific-atlantic-water-flow",
  },
  {
    title: "Surrounded Regions",
    leetcode_num: 130,
    difficulty: "medium",
    topic: "Graphs",
    slug: "surrounded-regions",
  },
  {
    title: "Course Schedule",
    leetcode_num: 207,
    difficulty: "medium",
    topic: "Graphs",
    slug: "course-schedule",
  },
  {
    title: "Course Schedule II",
    leetcode_num: 210,
    difficulty: "medium",
    topic: "Graphs",
    slug: "course-schedule-ii",
  },
  {
    title: "Graph Valid Tree",
    leetcode_num: 261,
    difficulty: "medium",
    topic: "Graphs",
    slug: "graph-valid-tree",
  },
  {
    title: "Number of Connected Components in an Undirected Graph",
    leetcode_num: 323,
    difficulty: "medium",
    topic: "Graphs",
    slug: "number-of-connected-components-in-an-undirected-graph",
  },
  {
    title: "Redundant Connection",
    leetcode_num: 684,
    difficulty: "medium",
    topic: "Graphs",
    slug: "redundant-connection",
  },
  {
    title: "Word Ladder",
    leetcode_num: 127,
    difficulty: "hard",
    topic: "Graphs",
    slug: "word-ladder",
  },

  // Advanced Graphs
  {
    title: "Reconstruct Itinerary",
    leetcode_num: 332,
    difficulty: "hard",
    topic: "Advanced Graphs",
    slug: "reconstruct-itinerary",
  },
  {
    title: "Min Cost to Connect All Points",
    leetcode_num: 1584,
    difficulty: "medium",
    topic: "Advanced Graphs",
    slug: "min-cost-to-connect-all-points",
  },
  {
    title: "Network Delay Time",
    leetcode_num: 743,
    difficulty: "medium",
    topic: "Advanced Graphs",
    slug: "network-delay-time",
  },
  {
    title: "Swim in Rising Water",
    leetcode_num: 778,
    difficulty: "hard",
    topic: "Advanced Graphs",
    slug: "swim-in-rising-water",
  },
  {
    title: "Alien Dictionary",
    leetcode_num: 269,
    difficulty: "hard",
    topic: "Advanced Graphs",
    slug: "alien-dictionary",
  },
  {
    title: "Cheapest Flights Within K Stops",
    leetcode_num: 787,
    difficulty: "medium",
    topic: "Advanced Graphs",
    slug: "cheapest-flights-within-k-stops",
  },

  // 1-D Dynamic Programming
  {
    title: "Climbing Stairs",
    leetcode_num: 70,
    difficulty: "easy",
    topic: "1-D Dynamic Programming",
    slug: "climbing-stairs",
  },
  {
    title: "Min Cost Climbing Stairs",
    leetcode_num: 746,
    difficulty: "easy",
    topic: "1-D Dynamic Programming",
    slug: "min-cost-climbing-stairs",
  },
  {
    title: "House Robber",
    leetcode_num: 198,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "house-robber",
  },
  {
    title: "House Robber II",
    leetcode_num: 213,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "house-robber-ii",
  },
  {
    title: "Longest Palindromic Substring",
    leetcode_num: 5,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "longest-palindromic-substring",
  },
  {
    title: "Palindromic Substrings",
    leetcode_num: 647,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "palindromic-substrings",
  },
  {
    title: "Decode Ways",
    leetcode_num: 91,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "decode-ways",
  },
  {
    title: "Coin Change",
    leetcode_num: 322,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "coin-change",
  },
  {
    title: "Maximum Product Subarray",
    leetcode_num: 152,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "maximum-product-subarray",
  },
  {
    title: "Word Break",
    leetcode_num: 139,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "word-break",
  },
  {
    title: "Longest Increasing Subsequence",
    leetcode_num: 300,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "longest-increasing-subsequence",
  },
  {
    title: "Partition Equal Subset Sum",
    leetcode_num: 416,
    difficulty: "medium",
    topic: "1-D Dynamic Programming",
    slug: "partition-equal-subset-sum",
  },

  // 2-D Dynamic Programming
  {
    title: "Unique Paths",
    leetcode_num: 62,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "unique-paths",
  },
  {
    title: "Longest Common Subsequence",
    leetcode_num: 1143,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "longest-common-subsequence",
  },
  {
    title: "Best Time to Buy and Sell Stock with Cooldown",
    leetcode_num: 309,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "best-time-to-buy-and-sell-stock-with-cooldown",
  },
  {
    title: "Coin Change II",
    leetcode_num: 518,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "coin-change-ii",
  },
  {
    title: "Target Sum",
    leetcode_num: 494,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "target-sum",
  },
  {
    title: "Interleaving String",
    leetcode_num: 97,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "interleaving-string",
  },
  {
    title: "Longest Increasing Path in a Matrix",
    leetcode_num: 329,
    difficulty: "hard",
    topic: "2-D Dynamic Programming",
    slug: "longest-increasing-path-in-a-matrix",
  },
  {
    title: "Distinct Subsequences",
    leetcode_num: 115,
    difficulty: "hard",
    topic: "2-D Dynamic Programming",
    slug: "distinct-subsequences",
  },
  {
    title: "Edit Distance",
    leetcode_num: 72,
    difficulty: "medium",
    topic: "2-D Dynamic Programming",
    slug: "edit-distance",
  },
  {
    title: "Burst Balloons",
    leetcode_num: 312,
    difficulty: "hard",
    topic: "2-D Dynamic Programming",
    slug: "burst-balloons",
  },
  {
    title: "Regular Expression Matching",
    leetcode_num: 10,
    difficulty: "hard",
    topic: "2-D Dynamic Programming",
    slug: "regular-expression-matching",
  },

  // Greedy
  {
    title: "Maximum Subarray",
    leetcode_num: 53,
    difficulty: "medium",
    topic: "Greedy",
    slug: "maximum-subarray",
  },
  {
    title: "Jump Game",
    leetcode_num: 55,
    difficulty: "medium",
    topic: "Greedy",
    slug: "jump-game",
  },
  {
    title: "Jump Game II",
    leetcode_num: 45,
    difficulty: "medium",
    topic: "Greedy",
    slug: "jump-game-ii",
  },
  {
    title: "Gas Station",
    leetcode_num: 134,
    difficulty: "medium",
    topic: "Greedy",
    slug: "gas-station",
  },
  {
    title: "Hand of Straights",
    leetcode_num: 846,
    difficulty: "medium",
    topic: "Greedy",
    slug: "hand-of-straights",
  },
  {
    title: "Merge Triplets to Form Target Triplet",
    leetcode_num: 1899,
    difficulty: "medium",
    topic: "Greedy",
    slug: "merge-triplets-to-form-target-triplet",
  },
  {
    title: "Partition Labels",
    leetcode_num: 763,
    difficulty: "medium",
    topic: "Greedy",
    slug: "partition-labels",
  },
  {
    title: "Valid Parenthesis String",
    leetcode_num: 678,
    difficulty: "medium",
    topic: "Greedy",
    slug: "valid-parenthesis-string",
  },

  // Intervals
  {
    title: "Insert Interval",
    leetcode_num: 57,
    difficulty: "medium",
    topic: "Intervals",
    slug: "insert-interval",
  },
  {
    title: "Merge Intervals",
    leetcode_num: 56,
    difficulty: "medium",
    topic: "Intervals",
    slug: "merge-intervals",
  },
  {
    title: "Non-overlapping Intervals",
    leetcode_num: 435,
    difficulty: "medium",
    topic: "Intervals",
    slug: "non-overlapping-intervals",
  },
  {
    title: "Meeting Rooms",
    leetcode_num: 252,
    difficulty: "easy",
    topic: "Intervals",
    slug: "meeting-rooms",
  },
  {
    title: "Meeting Rooms II",
    leetcode_num: 253,
    difficulty: "medium",
    topic: "Intervals",
    slug: "meeting-rooms-ii",
  },
  {
    title: "Minimum Interval to Include Each Query",
    leetcode_num: 1851,
    difficulty: "hard",
    topic: "Intervals",
    slug: "minimum-interval-to-include-each-query",
  },

  // Math & Geometry
  {
    title: "Rotate Image",
    leetcode_num: 48,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "rotate-image",
  },
  {
    title: "Spiral Matrix",
    leetcode_num: 54,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "spiral-matrix",
  },
  {
    title: "Set Matrix Zeroes",
    leetcode_num: 73,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "set-matrix-zeroes",
  },
  {
    title: "Happy Number",
    leetcode_num: 202,
    difficulty: "easy",
    topic: "Math & Geometry",
    slug: "happy-number",
  },
  {
    title: "Plus One",
    leetcode_num: 66,
    difficulty: "easy",
    topic: "Math & Geometry",
    slug: "plus-one",
  },
  {
    title: "Pow(x, n)",
    leetcode_num: 50,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "powx-n",
  },
  {
    title: "Multiply Strings",
    leetcode_num: 43,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "multiply-strings",
  },
  {
    title: "Detect Squares",
    leetcode_num: 2013,
    difficulty: "medium",
    topic: "Math & Geometry",
    slug: "detect-squares",
  },

  // Bit Manipulation
  {
    title: "Single Number",
    leetcode_num: 136,
    difficulty: "easy",
    topic: "Bit Manipulation",
    slug: "single-number",
  },
  {
    title: "Number of 1 Bits",
    leetcode_num: 191,
    difficulty: "easy",
    topic: "Bit Manipulation",
    slug: "number-of-1-bits",
  },
  {
    title: "Counting Bits",
    leetcode_num: 338,
    difficulty: "easy",
    topic: "Bit Manipulation",
    slug: "counting-bits",
  },
  {
    title: "Reverse Bits",
    leetcode_num: 190,
    difficulty: "easy",
    topic: "Bit Manipulation",
    slug: "reverse-bits",
  },
  {
    title: "Missing Number",
    leetcode_num: 268,
    difficulty: "easy",
    topic: "Bit Manipulation",
    slug: "missing-number",
  },
  {
    title: "Sum of Two Integers",
    leetcode_num: 371,
    difficulty: "medium",
    topic: "Bit Manipulation",
    slug: "sum-of-two-integers",
  },
  {
    title: "Reverse Integer",
    leetcode_num: 7,
    difficulty: "medium",
    topic: "Bit Manipulation",
    slug: "reverse-integer",
  },
];

export const TOPIC_NAMES = NEETCODE_TOPICS.map((t) => t.name);
